### ISSUE TITLE
Improve images on the website

### ISSUE THREAD

**Issue by lolmos** [lolmos/statictestting#171]
- [ ]  get slider to have tints for loading images
- [ ] fix slider leaving blank space to the right
- [ ] create tints for each bu or listing based on formula so it loads before. make basics have image transarency to show tints
- [ ] make preloader image with the branded H
- [ ]  test making ultra low rez background images before loading.
