### ISSUE TITLE
Write content for 3 Premium events in Spanish AND English

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#26]
#### Tribu Salsa Night
- [x] Event title
- [x] Event date
- [x] Start time and end time
- [x] Price 
- [x] Event type(s) (see #28)
- [x] Short event description
- [x] Event amenities (see #25)
- [x] Contact phone number 
- [x] Location (name)
## Has fields for the following meta data tags
- [x] Meta title
- [x] Meta description
- [x] OG title
- [x] OG description
- [x] Twitter title
- [x] Twitter description

#### Yoga Casa Las Tortugas
- [x] Event title
- [x] Event date
- [x] Start time and end time
- [x] Price 
- [x] Event type(s) (see #28)
- [x] Short event description
- [x] Event amenities (see #25)
- [x] Contact phone number 
- [x] Location (name)
## Has fields for the following meta data tags
- [x] Meta title
- [x] Meta description
- [x] OG title
- [x] OG description
- [x] Twitter title
- [x] Twitter description

#### Event i love me wellness
Get info from here
https://www.facebook.com/ilovemewellness/posts/1209013279156672
- [x] Event title
- [x] Event date
- [x] Start time and end time
- [x] Price 
- [x] Event type(s) (see #28)
- [x] Short event description
- [x] Event amenities (see #25)
- [x] Contact phone number 
- [x] Location (name)
## Has fields for the following meta data tags
- [x] Meta title
- [x] Meta description
- [x] OG title
- [x] OG description
- [ ] Twitter title
- [x] Twitter description

**Comment by Loubielou** [comment]
Not going to move this from here because you have technical things to write (it looks like it anyway), but all the short descriptions for the three events are written and in the content document in Dropbox. Hope this helps! :) xxxx P.s. They are in English and need to be translated.

**Comment by angievanhegan** [comment]
@lolmos I've moved into into 'in progress' because that's what the status seems to be.

**Comment by angievanhegan** [comment]
@lolmos who should be checking this? Can you assign it to them?
