### ISSUE TITLE
Write content for 3 basic events in Spanish AND English

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#27]
Images in #29

#### Baseball game
- [x] Event title
- [x] Event date
- [x] Start time and end time
- [x] Price 
- [x] Event type(s) (see #28)
- [x] Short event description
- [x] Event amenities (see #25)
- [x] Contact phone number 
- [x] Location (name)

#### Yoga in the water
- [x] Event title
- [x] Event date
- [x] Start time and end time
- [x] Price 
- [x] Event type(s) (see #28)
- [x] Short event description
- [x] Event amenities (see #25)
- [x] Contact phone number 
- [x] Location (name)

#### Cinema (just one film)
- [x] Event title
- [x] Event date
- [x] Start time and end time
- [x] Price 
- [x] Event type(s) (see #28)
- [x] Short event description
- [x] Event amenities (see #25)
- [x] Contact phone number 
- [x] Location (name)

**Comment by lolmos** [comment]
added 3 movies for the week end as that is the format they manage

**Comment by angievanhegan** [comment]
@lolmos Do you need @Loubielou to check this?
